### ISSUE TITLE
Network Error on hitting "Attempt" for specific kata only

### ISSUE THREAD

**Issue by Bubbler-4** [Codewars/codewars.com#1259]
I encountered this issue when I was trying to solve [Blind4Basic's Unique Digit Sequence (beta)](https://www.codewars.com/kata/unique-digit-sequence-ii-optimization-problem), which is Python-only.

The Network Error message was shown whenever I hit "Attempt" button with my solution. "Run Sample Tests" worked just fine. I tried both Python versions (2.7.3, 3.4.3) but neither worked.

I waited for around 6 hours hoping that the issue could resolve itself, but it was not the case. I opened the console and hit "Attempt" again, and found the following message, possibly directing the cause to Red server access permission:

> Failed to load https://runner-red.codewars.com/run: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cr-red.codewars.com' is therefore not allowed access. The response had HTTP status code 403.

> Error: Network Error
> at t.exports (https://cr-red.codewars.com/static/js/vendor.946ea95ea6ab4b61034c.js:11:44451)
> at XMLHttpRequest.p.onerror (https://cr-red.codewars.com/static/js/vendor.946ea95ea6ab4b61034c.js:11:43256)
> at XMLHttpRequest.r (https://cr-red.codewars.com/static/js/vendor.946ea95ea6ab4b61034c.js:54:41043)

Notably, I did not encounter any issue solving other katas in JS, C++, and even another Python kata. Also, I'm pretty sure that I still have valid Red access because I can see streaks and execution output before it's formatted.

**Comment by Bubbler-4** [comment]
Looks like the corporate firewall was intercepting the certificate; worked fine when I tried submit at home :)
