### ISSUE TITLE
Kumite search does not reduce the list displayed

### ISSUE THREAD

**Issue by schellingerhout** [codewars/codewars.com#2817]
Type a keyword, selecting a language or checking the box to "show only mine" has no effect on the list of Kumite displayed

Go to the Kumite page, and attempt any of the above, notice that the list of Kumite does not change.

Behavior similar to the Kata page where enter (return) after a keyword filters the list, similarly, changing the programming language filters the list

- Windows 10
- I only tested with Chromium based browsers Edge 105.0.1343.42, Brave 1.43.93, and Chrome 105.0.5195.127

**Comment by kazk** [comment]
I cannot reproduce the issue. The filters and search input are working as expected for me.

Can you try in Incognito/Private window without any extensions?

**Comment by schellingerhout** [comment]
I tried with incognito as well

**Comment by kazk** [comment]
Do you see any errors in dev console?

I get this:

![image](https://user-images.githubusercontent.com/639336/191135263-25183959-5d82-4214-b701-7cb16af41362.png)

**Comment by schellingerhout** [comment]
Changing the language to "C"

```
kumite:4 
        
       The value "320px" for key "width" was truncated to its numeric prefix.
index_controller.js:28 
        
       Uncaught TypeError: Cannot read properties of null (reading 'checked')
    at Z4.filterUrl (index_controller.js:28:49)
    at Z4.filter (index_controller.js:47:27)
    at Z4.search (index_controller.js:42:10)
    at #personal sl-change, #secrets sl-change, #language_filter sl-change (index_controller.js:59:10)
    at x.s (control.js:94:15)
    at HTMLDivElement.dispatch (jquery.js:5430:27)
    at yt.handle (jquery.js:5234:28)
    at HTMLDivElement.n (helpers.js:73:23)
    at m (chunk.UY5AQKHP.js:13:6)
    at x.handleValueChange (chunk.TW7SELQV.js:224:5)
filterUrl @ index_controller.js:28
filter @ index_controller.js:47
search @ index_controller.js:42
#personal sl-change, #secrets sl-change, #language_filter sl-change @ index_controller.js:59
s @ control.js:94
dispatch @ jquery.js:5430
yt.handle @ jquery.js:5234
n @ helpers.js:73
m @ chunk.UY5AQKHP.js:13
handleValueChange @ chunk.TW7SELQV.js:224
await in handleValueChange (async)
i.update @ chunk.W6MGCO4G.js:20
performUpdate @ chunk.ZU3WVWU5.js:223
scheduleUpdate @ chunk.ZU3WVWU5.js:210
_$E_ @ chunk.ZU3WVWU5.js:206
await in _$E_ (async)
requestUpdate @ chunk.ZU3WVWU5.js:197
set @ chunk.ZU3WVWU5.js:106
handleMenuSelect @ chunk.TW7SELQV.js:171
handleEvent @ chunk.ZU3WVWU5.js:527
m @ chunk.UY5AQKHP.js:13
handleClick @ chunk.GNNQIW5N.js:86
handleEvent @ chunk.ZU3WVWU5.js:527
```
Changing the search term to "div" and hitting enter
```
kumite:4 
        
       The value "320px" for key "width" was truncated to its numeric prefix.
index_controller.js:28 
        
       Uncaught TypeError: Cannot read properties of null (reading 'checked')
    at Z4.filterUrl (index_controller.js:28:49)
    at Z4.filter (index_controller.js:47:27)
    at Z4.search (index_controller.js:42:10)
    at #personal sl-change, #secrets sl-change, #language_filter sl-change (index_controller.js:59:10)
    at x.s (control.js:94:15)
    at HTMLDivElement.dispatch (jquery.js:5430:27)
    at yt.handle (jquery.js:5234:28)
    at HTMLDivElement.n (helpers.js:73:23)
    at m (chunk.UY5AQKHP.js:13:6)
    at x.handleValueChange (chunk.TW7SELQV.js:224:5)
filterUrl @ index_controller.js:28
filter @ index_controller.js:47
search @ index_controller.js:42
#personal sl-change, #secrets sl-change, #language_filter sl-change @ index_controller.js:59
s @ control.js:94
dispatch @ jquery.js:5430
yt.handle @ jquery.js:5234
n @ helpers.js:73
m @ chunk.UY5AQKHP.js:13
handleValueChange @ chunk.TW7SELQV.js:224
await in handleValueChange (async)
i.update @ chunk.W6MGCO4G.js:20
performUpdate @ chunk.ZU3WVWU5.js:223
scheduleUpdate @ chunk.ZU3WVWU5.js:210
_$E_ @ chunk.ZU3WVWU5.js:206
await in _$E_ (async)
requestUpdate @ chunk.ZU3WVWU5.js:197
set @ chunk.ZU3WVWU5.js:106
handleMenuSelect @ chunk.TW7SELQV.js:171
handleEvent @ chunk.ZU3WVWU5.js:527
m @ chunk.UY5AQKHP.js:13
handleClick @ chunk.GNNQIW5N.js:86
handleEvent @ chunk.ZU3WVWU5.js:527
onloadwff.js:71 
        
       Assertion failed: Input argument is not an HTMLInputElement
getFormProfile @ onloadwff.js:71
setFieldValue @ onloadwff.js:71
formKeydownListener @ onloadwff.js:71
index_controller.js:28 
        
       Uncaught TypeError: Cannot read properties of null (reading 'checked')
    at Z4.filterUrl (index_controller.js:28:49)
    at Z4.filter (index_controller.js:47:27)
    at Z4.search (index_controller.js:42:10)
    at #search_form submit (index_controller.js:65:10)
    at HTMLFormElement.s (control.js:94:15)
    at HTMLBodyElement.dispatch (jquery.js:5430:27)
    at yt.handle (jquery.js:5234:28)
    at HTMLBodyElement.n (helpers.js:73:23)
    at Wt.submit (chunk.S6I2SNDG.js:173:14)
    at chunk.OKGOLR6A.js:147:37
    at n (helpers.js:73:23)
filterUrl @ index_controller.js:28
filter @ index_controller.js:47
search @ index_controller.js:42
#search_form submit @ index_controller.js:65
s @ control.js:94
dispatch @ jquery.js:5430
yt.handle @ jquery.js:5234
n @ helpers.js:73
submit @ chunk.S6I2SNDG.js:173
(anonymous) @ chunk.OKGOLR6A.js:147
n @ helpers.js:73
setTimeout (async)
(anonymous) @ trycatch.js:86
handleKeyDown @ chunk.OKGOLR6A.js:145
handleEvent @ chunk.ZU3WVWU5.js:527
```

If I open the URL with the query in the address https://www.codewars.com/kumite?q=div&language=c it works.

**Comment by kazk** [comment]
I found the bug. I wasn't able to reproduce because this doesn't happen when using admin account :man_facepalming:. 

Thanks for reporting!

**Comment by kazk** [comment]
Deployed the fix
