### ISSUE TITLE
500 error on code submit

### ISSUE THREAD

**Issue by yevgeny-mihailin** [Codewars/codewars.com#498]
kata:
https://www.codewars.com/kata/catch-mad-mars-bar-max/train/javascript

on code submit i have this output:
500: error

Description: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
   at fromObject (buffer.js:287:9)
   at Function.Buffer.from (buffer.js:133:10)
   at new Buffer (buffer.js:112:17)
   at Object.module.exports.decrypt (/server/lib/cipher.js:8:18)
   at transformBody (/server/lib/routes/run.js:41:32)
   at module.exports (/server/lib/routes/run.js:14:15)
   at Layer.handle [as handle_request](/server/node_modules/express/lib/router/layer.js:95:5)
   at next (/server/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/server/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request](/server/node_modules/express/lib/router/layer.js:95:5)
   at /server/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/server/node_modules/express/lib/router/index.js:330:12)
   at next (/server/node_modules/express/lib/router/index.js:271:10)
   at serveStatic (/server/node_modules/serve-static/index.js:75:16)
   at Layer.handle [as handle_request](/server/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/server/node_modules/express/lib/router/index.js:312:13)

This error was caused due to an issue processing the web request, not because of an issue executing your code.

**Comment by DestyNova** [comment]
I'm seeing this now on the [word values](https://www.codewars.com/kata/word-values/train/haskell) problem.

**Comment by Voileexperiments** [comment]
#1370
