### ISSUE TITLE
TypeError: buffer.stdout.push is not a function

### ISSUE THREAD

**Issue by sriedel** [Codewars/codewars.com#774]
I'm getting this error semi-frequently when training on ruby katas that are dealing with potentially large numbers of iterations:

```
/runner/lib/shovel.js:181
            buffer.stdout.push(text);
                          ^

TypeError: buffer.stdout.push is not a function
    at Socket. (/runner/lib/shovel.js:181:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

I've seen this error in several different katas over the past few days. The error pops up pretty much immediately, so this is not due to the timeout of 12 seconds for the test run. At times the error alternates with an error message indicating that the max buffer size has been exceeded (in which case it would still be nice to see the content of the maxed out buffer :), but that's another issue). 

Currently I'm seeing this error reproducably on the Beta Kata "Clustering Arrays" using the following code as a solution:

```
class Clusterer
	attr_reader :tuples
  
  def initialize(tuples)
  	@tuples = tuples
    puts "Got tuples: #{@tuples.inspect}"
  end

  def flatten  
  	flattened = tuples.dup
    merge_index = 0
    
    while merge_index < flattened.size
    	inspect_index = merge_index + 1
      while inspect_index < flattened.size
      	puts "Processing #{flattened.inspect}"
      	ary_to_merge_into = flattened[merge_index]
        ary_to_inspect    = flattened[inspect_index]
        puts "Inspecting #{ary_to_inspect.inspect} for #{ary_to_merge_into.inspect}"
        
      	if (ary_to_merge_into & ary_to_inspect).empty?
        	puts "No overlap; skip"
          inspect_index += 1
       	else
        	ary_to_merge_into.concat( ary_to_inspect )
          ary_to_merge_into.uniq!
          flattened.delete_at( inspect_index )
          puts "Merged: #{flattened.inspect}"
        end
      end
      merge_index += 1
    end
    flattened.map { |ary| ary.sort }
  end
end
```

Interestingly, if you change the line `flattened.map { |ary| ary.sort }` to just `flattened` the error disappears and the expected "Tests failed" message is displayed.

**Comment by sriedel** [comment]
Addendum: Changing the last few rows of the flatten method to read
```
    flattened.map! { |x| x.sort! }
    puts flattened.inspect
    nil
```
so that one can see what would be returned by the original method code above, the output would be `[[1, 2, 3, 4], [5, 6]]`, which corresponds to the correct solution for the unit test. Maybe it has to do with the specific content of nested arrays, or the message that would be output by the unit tests either for the success of the immediate one or of an error message for a following test.

**Comment by sriedel** [comment]
Having played around further, after removing all `puts` lines, everything runs as it should. So it seems to be connected to the amount of debug information being output, causing the output buffer to be exceeded and for some reason not triggering the Max Buffer Exceeded condition.
